feat: initial test for rollbar/rollbar v4
rollbar/rollbar-php-symfony-bundle pull request #86
Opened 2023-02-02 17:05 UTC by Chris53897

https://github.com/rollbar/rollbar-php-symfony-bundle/issues/85

We need to wait after rollbar/rollbar v4 is stable.
After this it can be changed "rollbar/rollbar": "^3.1|^4.0",

This is just a proof of concept for changes in version 4.

2023-03-22 11:19 UTC, danielmorell commented
I think we will also need to make some changes to the `Tests/Fixtures/ErrorHandler` class. It is not compatible with Monolog 3. We may need one class for Monolog 1 and 2 and another for Monolog 3.

2023-03-25 02:34 UTC, Chris53897 commented
Thanks for the info. I will have a look after Version 4 is stable.

2023-04-11 10:09 UTC, danielmorell requested changes
It looks like we have not needed the `Tests\Fixtures\ErrorHandler` class since v3. If you remove that class and update the version constraint for `rollbar/rollbar` in the `composer.json` to `"^3.1 || ^4.0"` I think the tests should pass.

2023-04-16 11:13 UTC, Chris53897 commented
I bumped the symfony version from 6.0 to 6.2.
This is the only one from the 6.x branch that is maintained https://symfony.com/releases#maintained-symfony-branches

2023-05-02 12:03 UTC, danielmorell approved these changes
This looks great! Thank you @Chris53897!

2023-05-02 12:03 UTC, merged